apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: angular-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: angualr-frontend                                  # 6
    spec:
      containers:
        - image: ctmsacr.azurecr.io/angular:{{.Values.image.tag}}
          imagePullPolicy: Always                         # 7
          name: angular-frontend
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: icsaksregistry  
