apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: angular
  namespace: ingress-nginx
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                  
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1   
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: shreyans25/angular-test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-svc
  namespace: ingress-nginx
  labels:
spec:
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: angular
