apiVersion: v1
kind: Service              # 1
metadata:
  name: angular-frontend-lb
spec:      # 2
  ports:
  - port: 5000              # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: angualr-frontend       # 7