version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - CUSTOM_TAG=$(date +%s)
    - docker build -f Springboot-kube/Dockerfile -t $IMAGE_REPO_NAME:$CUSTOM_TAG .
    - docker tag $IMAGE_REPO_NAME:$CUSTOM_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CUSTOM_TAG
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CUSTOM_TAG
