version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo [PHASE] Entered the install phase...
      - # 1. We install aws-cli (Alpine Linux  )
      - apt update
      - pip install awscli
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - CUSTOM_TAG=$(date +%s)
    - docker build . -t $IMAGE_REPO_NAME:$CUSTOM_TAG
    - docker tag $IMAGE_REPO_NAME:$CUSTOM_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CUSTOM_TAG
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CUSTOM_TAG
    - sed -i "s/BUILD_ID/CUSTOM_TAG/g" python-deployment.yaml
