apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: python
spec:
  replicas: 2
  selector:
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        name: python
        image: 715146130151.dkr.ecr.us-east-1.amazonaws.com/microservices:python
        ports:
        - containerPort: 5000

